# Arrhythmia detection (1 - Normal, 0 - Abnormal beats), Dataset - ECG5000

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [15]:
dataset = pd.read_csv("ECG5000_test.csv")
dt1 = pd.read_csv("ECG5000_train.csv")

In [16]:
dataset.head()

attr    attr.1    attr.2    attr.3    attr.4    attr.5    attr.6  \
0 -0.112522 -2.827204 -3.773897 -4.349751 -4.376041 -3.474986 -2.181408   
1 -1.100878 -3.996840 -4.285843 -4.506579 -4.022377 -3.234368 -1.566126   
2 -0.567088 -2.593450 -3.874230 -4.584095 -4.187449 -3.151462 -1.742940   
3  0.490473 -1.914407 -3.616364 -4.318823 -4.268016 -3.881110 -2.993280   
4  0.800232 -0.874252 -2.384761 -3.973292 -4.338224 -3.802422 -2.534510   

     attr.7    attr.8    attr.9  ...  attr.131  attr.132  attr.133  attr.134  \
0 -1.818287 -1.250522 -0.477492  ...  0.792168  0.933541  0.796958  0.578621   
1 -0.992258 -0.754680  0.042321  ...  0.538356  0.656881  0.787490  0.724046   
2 -1.490658 -1.183580 -0.394229  ...  0.886073  0.531452  0.311377 -0.021919   
3 -1.671131 -1.333884 -0.965629  ...  0.350816  0.499111  0.600345  0.842069   
4 -1.783423 -1.594450 -0.753199  ...  1.148884  0.958434  1.059025  1.371682   

   attr.135  attr.136  attr.137  attr.138  attr.139  class  
0  0.257740  0.228077  0.123431  0.925286  0.193137      1  
1  0.555784  0.476333  0.773820  1.119621 -1.436250      1  
2 -0.713683 -0.532197  0.321097  0.904227 -0.421797      1  
3  0.952074  0.990133  1.086798  1.403011 -0.383564      1  
4  1.277392  0.960304  0.971020  1.614392  1.421456      1  

[5 rows x 141 columns]

In [17]:
dt1.head()

attr    attr.1    attr.2    attr.3    attr.4    attr.5    attr.6  \
0  3.690844  0.711414 -2.114092 -4.141007 -4.574472 -3.431909 -1.950791   
1 -1.348132 -3.996038 -4.226750 -4.251187 -3.477953 -2.228422 -1.808488   
2  1.024295 -0.590314 -1.916949 -2.806989 -3.527905 -3.638675 -2.779767   
3  0.545657 -1.014383 -2.316698 -3.634040 -4.196857 -3.758093 -3.194444   
4  0.661133 -1.552471 -3.124641 -4.313351 -4.017042 -3.005993 -1.832411   

     attr.7    attr.8    attr.9  ...  attr.131  attr.132  attr.133  attr.134  \
0 -1.107067 -0.632322  0.334577  ...  0.022847  0.188937  0.480932  0.629250   
1 -1.534242 -0.779861 -0.397999  ...  1.570938  1.591394  1.549193  1.193077   
2 -2.019031 -1.980754 -1.440680  ...  0.443502  0.827582  1.237007  1.235121   
3 -2.221764 -1.588554 -1.202146  ...  0.777530  1.119240  0.902984  0.554098   
4 -1.503886 -1.071705 -0.521316  ...  1.280823  1.494316  1.618764  1.447449   

   attr.135  attr.136  attr.137  attr.138  attr.139  class  
0  0.577291  0.665527  1.035997  1.492287 -1.905073      1  
1  0.515134  0.126274  0.267532  1.071148 -1.164009      1  
2  1.738103  1.800767  1.816301  1.473963  1.389767      1  
3  0.497053  0.418116  0.703108  1.064602 -0.044853      1  
4  1.238577  1.749692  1.986803  1.422756 -0.357784      1  

[5 rows x 141 columns]

In [18]:
dataset.shape

(500, 141)

In [19]:
dt1.shape

(4500, 141)

In [20]:
dfc=dataset.copy()

dfc['class']=dfc['class'].apply(lambda t: 0 if t!=1 else t)

In [21]:
dtc = dt1.copy()

dtc['class']=dtc['class'].apply(lambda t: 0 if t!=1 else t)

In [22]:
dfc.tail()

attr    attr.1    attr.2    attr.3    attr.4    attr.5    attr.6  \
495 -0.478577 -1.779959 -2.398159 -3.170112 -3.559732 -3.573956 -2.989770   
496 -1.325210 -2.480992 -2.965356 -3.342392 -3.176351 -2.891528 -2.369679   
497 -0.021964 -0.912434 -1.903353 -2.662829 -3.122156 -3.451490 -3.392982   
498  0.288011 -1.098020 -2.500250 -3.598599 -3.650608 -3.281587 -2.231601   
499 -1.133674 -2.702941 -3.120979 -3.558669 -3.312442 -2.607641 -1.354939   

       attr.7    attr.8    attr.9  ...  attr.131  attr.132  attr.133  \
495 -2.270605 -1.688277 -1.359872  ...  1.160884  1.456331  2.209421   
496 -1.598750 -1.071751 -0.891843  ... -0.172154 -0.864803 -1.549854   
497 -2.929937 -2.256294 -1.690706  ...  1.339479  1.457995  2.128078   
498 -1.250656 -1.072574 -0.434310  ... -0.029242  0.071414  0.118161   
499 -1.014740 -0.796023 -0.259599  ... -3.206942 -2.941677 -2.557140   

     attr.134  attr.135  attr.136  attr.137  attr.138  attr.139  class  
495  2.507175  2.198534  1.705849  1.492642  1.561890  1.520161      0  
496 -2.460243 -3.366562 -3.466546 -2.718380 -1.855209 -1.539958      0  
497  2.630759  2.295748  1.764967  1.444280  1.432347  1.457028      0  
498 -0.071967 -0.171214  0.131211  0.049872  0.010915 -0.081534      0  
499 -1.487946 -1.118880 -0.737113 -0.110840  0.001858 -0.122639      0  

[5 rows x 141 columns]

In [23]:
dtc.tail()

attr    attr.1    attr.2    attr.3    attr.4    attr.5    attr.6  \
4495 -1.122969 -2.252925 -2.867628 -3.358605 -3.167849 -2.638360 -1.664162   
4496 -0.547705 -1.889545 -2.839779 -3.457912 -3.929149 -3.966026 -3.492560   
4497 -1.351779 -2.209006 -2.520225 -3.061475 -3.065141 -3.030739 -2.622720   
4498 -1.124432 -1.905039 -2.192707 -2.904320 -2.900722 -2.761252 -2.569705   
4499  0.728813  0.192597 -0.733884 -1.779456 -2.345908 -2.977565 -3.380053   

        attr.7    attr.8    attr.9  ...  attr.131  attr.132  attr.133  \
4495 -0.935655 -0.866953 -0.645363  ... -0.472419 -1.310147 -2.029521   
4496 -2.695269 -1.849691 -1.374321  ...  1.258419  1.907529  2.280888   
4497 -2.044092 -1.295874 -0.733839  ... -1.512234 -2.076075 -2.586042   
4498 -2.043893 -1.490538 -0.938473  ... -2.821782 -3.268355 -3.634981   
4499 -3.417164 -3.030925 -2.313867  ...  1.267275  1.678989  2.483389   

      attr.134  attr.135  attr.136  attr.137  attr.138  attr.139  class  
4495 -3.221294 -4.176790 -4.009720 -2.874136 -2.008369 -1.808334      0  
4496  1.895242  1.437702  1.193433  1.261335  1.150449  0.804932      0  
4497 -3.322799 -3.627311 -3.437038 -2.260023 -1.577823 -0.684531      0  
4498 -3.168765 -2.245878 -1.262259 -0.443307 -0.559769  0.108568      0  
4499  2.569073  2.122891  1.753963  1.538975  1.713781  1.309382      0  

[5 rows x 141 columns]

In [25]:
file = 'test.csv'
dtc.to_csv(file)

In [26]:
filename = 'train.csv'
dfc.to_csv(filename)

In [27]:
X_train = dfc.iloc[:,:-1].values
y_train = dfc.iloc[:,-1].values
X_test = dtc.iloc[:,:-1].values
y_test = dtc.iloc[:,-1].values

# Kernal SVM

In [28]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(X_train,y_train)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [29]:
print(classifier.predict([[0.087630577,-1.7534903,-3.3044731,-4.7046566,-4.6864151,-3.6118167,-2.2672676,-1.570893,-1.4177903,-0.50078809,-0.22517739,-0.30883362,-0.21473324,-0.21450921,-0.22312107,-0.26233599,-0.2118159,-0.29909881,-0.25995633,-0.31610955,-0.25866848,-0.28714668,-0.36685535,-0.30598032,-0.41670806,-0.40230307,-0.3815541,-0.51989677,-0.52095179,-0.59691915,-0.6507003,-0.67963616,-0.75152681,-0.72522391,-0.83070065,-0.80731727,-0.84838836,-0.74455386,-0.69997298,-0.75435259,-0.62191821,-0.53394237,-0.3965959,-0.22089032,-0.17931625,-0.00948034,-0.024018025,0.041459691,0.094492517,0.083212059,0.099031316,0.045914253,0.10951946,0.168162,0.26346944,0.13610056,0.15883825,0.08980313,0.14660419,0.19676887,0.26898346,0.23726297,0.18635578,0.24141723,0.27842589,0.38315578,0.38957693,0.39354878,0.57738569,0.58774864,0.58188293,0.5449169,0.65788513,0.60177743,0.64273411,0.69906231,0.6801103,0.69863975,0.71617522,0.66862611,0.6718266,0.57504464,0.5292125,0.54333826,0.60328119,0.55471386,0.56362046,0.48903431,0.44695034,0.45643246,0.39325248,0.44143912,0.44738863,0.27405506,0.36460866,0.40121863,0.44788969,0.54780929,0.6420901,0.78832807,0.74980141,0.82085218,0.96416033,1.0618841,1.3408602,1.1378081,0.86401264,0.6839801,0.62842387,0.50113433,0.49129218,0.46193736,0.32981245,0.1204151,-0.14196808,-0.19517724,-0.10265211,-0.076308425,-0.11651106,-0.19168563,-0.23429165,-0.16112658,-0.14536342,-0.21218169,-0.13568405,-0.1334405,-0.17007668,-0.035913592,0.33224263,1.0632505,1.575754,1.7090456,2.1429259,2.393528,1.92555,1.0276237,0.57345293,0.19297149,-0.64868286,-2.4410678]]))

[1]


In [30]:
print(classifier.predict([[0.95324235,0.77127376,0.30104506,-0.49906226,-0.85264837,-1.1836698,-1.6161765,-1.8540788,-1.8362536,-1.585443,-1.1717503,-0.81657409,-0.50372297,-0.41442852,-0.33109064,-0.007735187,0.44585482,0.55020167,0.485564,0.46952353,0.45863731,0.44977674,0.44255356,0.45164861,0.38938355,0.41765102,0.47561697,0.48011944,0.4714523,0.51364186,0.49884647,0.45882017,0.46417123,0.49619338,0.52006678,0.45337824,0.38731001,0.34825093,0.33235425,0.37277642,0.37231748,0.35814382,0.23794529,0.28734231,0.27664904,0.23634723,0.30709014,0.21288045,0.19444063,0.17747019,0.12437241,0.14537112,0.091502378,0.0572156,0.089751632,0.041898278,0.006256359,-0.001473174,0.009545261,-0.016361119,-0.035928219,-0.022056776,-0.06721399,-0.10499679,-0.10498087,-0.040286083,-0.09412929,-0.063551018,-0.033710071,-0.093066508,-0.043366841,-0.012832935,0.022640182,0.076042146,0.1468543,0.23224265,0.20727474,0.26444977,0.34552017,0.40265865,0.44054955,0.40047669,0.36989898,0.49261908,0.53274279,0.49681144,0.52215329,0.4923576,0.47654693,0.49811527,0.61372306,0.65081585,0.59244265,0.564082,0.55887499,0.56927301,0.59964893,0.62936494,0.58104229,0.60408747,0.71617194,0.7008751,0.62324959,0.57666352,0.65516422,0.64825732,0.68778289,0.7692567,0.7479442,0.71640598,0.74205272,0.73662599,0.73663392,0.78961701,0.76739811,0.84600274,0.87858614,0.78740362,0.74231366,0.71967299,0.46785537,0.36299887,0.40673928,0.38550744,0.21627213,-0.08890634,-0.31885963,-0.62723796,-0.87164014,-1.1402709,-1.1562263,-1.3452832,-1.7758592,-2.0924899,-2.8118059,-3.1410959,-3.9596481,-4.2032912,-4.6628937,-3.2945586]]))

[0]


In [31]:
y_pred = classifier.predict(X_test)

In [32]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[1802   71]
 [   4 2623]]
0.9833333333333333


# Support Vector Machine

In [34]:
from sklearn.svm import SVC
svm = SVC(kernel='linear')
svm.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [35]:
print(svm.predict([[0.087630577,-1.7534903,-3.3044731,-4.7046566,-4.6864151,-3.6118167,-2.2672676,-1.570893,-1.4177903,-0.50078809,-0.22517739,-0.30883362,-0.21473324,-0.21450921,-0.22312107,-0.26233599,-0.2118159,-0.29909881,-0.25995633,-0.31610955,-0.25866848,-0.28714668,-0.36685535,-0.30598032,-0.41670806,-0.40230307,-0.3815541,-0.51989677,-0.52095179,-0.59691915,-0.6507003,-0.67963616,-0.75152681,-0.72522391,-0.83070065,-0.80731727,-0.84838836,-0.74455386,-0.69997298,-0.75435259,-0.62191821,-0.53394237,-0.3965959,-0.22089032,-0.17931625,-0.00948034,-0.024018025,0.041459691,0.094492517,0.083212059,0.099031316,0.045914253,0.10951946,0.168162,0.26346944,0.13610056,0.15883825,0.08980313,0.14660419,0.19676887,0.26898346,0.23726297,0.18635578,0.24141723,0.27842589,0.38315578,0.38957693,0.39354878,0.57738569,0.58774864,0.58188293,0.5449169,0.65788513,0.60177743,0.64273411,0.69906231,0.6801103,0.69863975,0.71617522,0.66862611,0.6718266,0.57504464,0.5292125,0.54333826,0.60328119,0.55471386,0.56362046,0.48903431,0.44695034,0.45643246,0.39325248,0.44143912,0.44738863,0.27405506,0.36460866,0.40121863,0.44788969,0.54780929,0.6420901,0.78832807,0.74980141,0.82085218,0.96416033,1.0618841,1.3408602,1.1378081,0.86401264,0.6839801,0.62842387,0.50113433,0.49129218,0.46193736,0.32981245,0.1204151,-0.14196808,-0.19517724,-0.10265211,-0.076308425,-0.11651106,-0.19168563,-0.23429165,-0.16112658,-0.14536342,-0.21218169,-0.13568405,-0.1334405,-0.17007668,-0.035913592,0.33224263,1.0632505,1.575754,1.7090456,2.1429259,2.393528,1.92555,1.0276237,0.57345293,0.19297149,-0.64868286,-2.4410678]]))

[1]


In [36]:
y_pred = svm.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[1790   83]
 [   8 2619]]
0.9797777777777777


# Naive Bayes

In [38]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [39]:
print(gnb.predict([[0.087630577,-1.7534903,-3.3044731,-4.7046566,-4.6864151,-3.6118167,-2.2672676,-1.570893,-1.4177903,-0.50078809,-0.22517739,-0.30883362,-0.21473324,-0.21450921,-0.22312107,-0.26233599,-0.2118159,-0.29909881,-0.25995633,-0.31610955,-0.25866848,-0.28714668,-0.36685535,-0.30598032,-0.41670806,-0.40230307,-0.3815541,-0.51989677,-0.52095179,-0.59691915,-0.6507003,-0.67963616,-0.75152681,-0.72522391,-0.83070065,-0.80731727,-0.84838836,-0.74455386,-0.69997298,-0.75435259,-0.62191821,-0.53394237,-0.3965959,-0.22089032,-0.17931625,-0.00948034,-0.024018025,0.041459691,0.094492517,0.083212059,0.099031316,0.045914253,0.10951946,0.168162,0.26346944,0.13610056,0.15883825,0.08980313,0.14660419,0.19676887,0.26898346,0.23726297,0.18635578,0.24141723,0.27842589,0.38315578,0.38957693,0.39354878,0.57738569,0.58774864,0.58188293,0.5449169,0.65788513,0.60177743,0.64273411,0.69906231,0.6801103,0.69863975,0.71617522,0.66862611,0.6718266,0.57504464,0.5292125,0.54333826,0.60328119,0.55471386,0.56362046,0.48903431,0.44695034,0.45643246,0.39325248,0.44143912,0.44738863,0.27405506,0.36460866,0.40121863,0.44788969,0.54780929,0.6420901,0.78832807,0.74980141,0.82085218,0.96416033,1.0618841,1.3408602,1.1378081,0.86401264,0.6839801,0.62842387,0.50113433,0.49129218,0.46193736,0.32981245,0.1204151,-0.14196808,-0.19517724,-0.10265211,-0.076308425,-0.11651106,-0.19168563,-0.23429165,-0.16112658,-0.14536342,-0.21218169,-0.13568405,-0.1334405,-0.17007668,-0.035913592,0.33224263,1.0632505,1.575754,1.7090456,2.1429259,2.393528,1.92555,1.0276237,0.57345293,0.19297149,-0.64868286,-2.4410678]]))

[1]


In [40]:
y_pred = gnb.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1814   59]
 [  89 2538]]
0.9671111111111111


# K-Nearest Neighbors

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [43]:
print(knn.predict([[0.087630577,-1.7534903,-3.3044731,-4.7046566,-4.6864151,-3.6118167,-2.2672676,-1.570893,-1.4177903,-0.50078809,-0.22517739,-0.30883362,-0.21473324,-0.21450921,-0.22312107,-0.26233599,-0.2118159,-0.29909881,-0.25995633,-0.31610955,-0.25866848,-0.28714668,-0.36685535,-0.30598032,-0.41670806,-0.40230307,-0.3815541,-0.51989677,-0.52095179,-0.59691915,-0.6507003,-0.67963616,-0.75152681,-0.72522391,-0.83070065,-0.80731727,-0.84838836,-0.74455386,-0.69997298,-0.75435259,-0.62191821,-0.53394237,-0.3965959,-0.22089032,-0.17931625,-0.00948034,-0.024018025,0.041459691,0.094492517,0.083212059,0.099031316,0.045914253,0.10951946,0.168162,0.26346944,0.13610056,0.15883825,0.08980313,0.14660419,0.19676887,0.26898346,0.23726297,0.18635578,0.24141723,0.27842589,0.38315578,0.38957693,0.39354878,0.57738569,0.58774864,0.58188293,0.5449169,0.65788513,0.60177743,0.64273411,0.69906231,0.6801103,0.69863975,0.71617522,0.66862611,0.6718266,0.57504464,0.5292125,0.54333826,0.60328119,0.55471386,0.56362046,0.48903431,0.44695034,0.45643246,0.39325248,0.44143912,0.44738863,0.27405506,0.36460866,0.40121863,0.44788969,0.54780929,0.6420901,0.78832807,0.74980141,0.82085218,0.96416033,1.0618841,1.3408602,1.1378081,0.86401264,0.6839801,0.62842387,0.50113433,0.49129218,0.46193736,0.32981245,0.1204151,-0.14196808,-0.19517724,-0.10265211,-0.076308425,-0.11651106,-0.19168563,-0.23429165,-0.16112658,-0.14536342,-0.21218169,-0.13568405,-0.1334405,-0.17007668,-0.035913592,0.33224263,1.0632505,1.575754,1.7090456,2.1429259,2.393528,1.92555,1.0276237,0.57345293,0.19297149,-0.64868286,-2.4410678]]))

[1]


In [44]:
y_pred = knn.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1788   85]
 [   2 2625]]
0.9806666666666667


# Decision Tree

In [46]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion='entropy')
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [47]:
print(dt.predict([[0.087630577,-1.7534903,-3.3044731,-4.7046566,-4.6864151,-3.6118167,-2.2672676,-1.570893,-1.4177903,-0.50078809,-0.22517739,-0.30883362,-0.21473324,-0.21450921,-0.22312107,-0.26233599,-0.2118159,-0.29909881,-0.25995633,-0.31610955,-0.25866848,-0.28714668,-0.36685535,-0.30598032,-0.41670806,-0.40230307,-0.3815541,-0.51989677,-0.52095179,-0.59691915,-0.6507003,-0.67963616,-0.75152681,-0.72522391,-0.83070065,-0.80731727,-0.84838836,-0.74455386,-0.69997298,-0.75435259,-0.62191821,-0.53394237,-0.3965959,-0.22089032,-0.17931625,-0.00948034,-0.024018025,0.041459691,0.094492517,0.083212059,0.099031316,0.045914253,0.10951946,0.168162,0.26346944,0.13610056,0.15883825,0.08980313,0.14660419,0.19676887,0.26898346,0.23726297,0.18635578,0.24141723,0.27842589,0.38315578,0.38957693,0.39354878,0.57738569,0.58774864,0.58188293,0.5449169,0.65788513,0.60177743,0.64273411,0.69906231,0.6801103,0.69863975,0.71617522,0.66862611,0.6718266,0.57504464,0.5292125,0.54333826,0.60328119,0.55471386,0.56362046,0.48903431,0.44695034,0.45643246,0.39325248,0.44143912,0.44738863,0.27405506,0.36460866,0.40121863,0.44788969,0.54780929,0.6420901,0.78832807,0.74980141,0.82085218,0.96416033,1.0618841,1.3408602,1.1378081,0.86401264,0.6839801,0.62842387,0.50113433,0.49129218,0.46193736,0.32981245,0.1204151,-0.14196808,-0.19517724,-0.10265211,-0.076308425,-0.11651106,-0.19168563,-0.23429165,-0.16112658,-0.14536342,-0.21218169,-0.13568405,-0.1334405,-0.17007668,-0.035913592,0.33224263,1.0632505,1.575754,1.7090456,2.1429259,2.393528,1.92555,1.0276237,0.57345293,0.19297149,-0.64868286,-2.4410678]]))

[1]


In [48]:
y_pred = dt.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1768  105]
 [  30 2597]]
0.97


# Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50,criterion='entropy')
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [51]:
print(rf.predict([[0.087630577,-1.7534903,-3.3044731,-4.7046566,-4.6864151,-3.6118167,-2.2672676,-1.570893,-1.4177903,-0.50078809,-0.22517739,-0.30883362,-0.21473324,-0.21450921,-0.22312107,-0.26233599,-0.2118159,-0.29909881,-0.25995633,-0.31610955,-0.25866848,-0.28714668,-0.36685535,-0.30598032,-0.41670806,-0.40230307,-0.3815541,-0.51989677,-0.52095179,-0.59691915,-0.6507003,-0.67963616,-0.75152681,-0.72522391,-0.83070065,-0.80731727,-0.84838836,-0.74455386,-0.69997298,-0.75435259,-0.62191821,-0.53394237,-0.3965959,-0.22089032,-0.17931625,-0.00948034,-0.024018025,0.041459691,0.094492517,0.083212059,0.099031316,0.045914253,0.10951946,0.168162,0.26346944,0.13610056,0.15883825,0.08980313,0.14660419,0.19676887,0.26898346,0.23726297,0.18635578,0.24141723,0.27842589,0.38315578,0.38957693,0.39354878,0.57738569,0.58774864,0.58188293,0.5449169,0.65788513,0.60177743,0.64273411,0.69906231,0.6801103,0.69863975,0.71617522,0.66862611,0.6718266,0.57504464,0.5292125,0.54333826,0.60328119,0.55471386,0.56362046,0.48903431,0.44695034,0.45643246,0.39325248,0.44143912,0.44738863,0.27405506,0.36460866,0.40121863,0.44788969,0.54780929,0.6420901,0.78832807,0.74980141,0.82085218,0.96416033,1.0618841,1.3408602,1.1378081,0.86401264,0.6839801,0.62842387,0.50113433,0.49129218,0.46193736,0.32981245,0.1204151,-0.14196808,-0.19517724,-0.10265211,-0.076308425,-0.11651106,-0.19168563,-0.23429165,-0.16112658,-0.14536342,-0.21218169,-0.13568405,-0.1334405,-0.17007668,-0.035913592,0.33224263,1.0632505,1.575754,1.7090456,2.1429259,2.393528,1.92555,1.0276237,0.57345293,0.19297149,-0.64868286,-2.4410678]]))

[1]


In [52]:
y_pred = rf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [53]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1784   89]
 [   5 2622]]
0.9791111111111112


# XGBoost

In [54]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [55]:
y_pred = rf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = xgb.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1781   92]
 [  14 2613]]


0.9764444444444444